### ISSUE TITLE
Need help using API functions

### ISSUE THREAD

**Issue by luispl77** [bengtmartensson/IrpTransmogrifier#258]
Hello,

I am trying to incorporate this API into a future open source Android app.
However, because i could not find example code for the API classes and functions, i am having trouble understanding what needs to be called.

What I am trying to do is very simple, its this exact functionality:

./irptransmogrifier.sh render --protocol NEC1 --nameengine "D=12,S=34,F=56" --raw
Freq=38400Hz[9024,4512,564,564,564,564,564,1692,564,1692,564,564,564,564,564,564,564,564,564,564,564,1692,564,564,564,564,564,564,564,1692,564,564,564,564,564,564,564,564,564,564,564,1692,564,1692,564,1692,564,564,564,564,564,1692,564,1692,564,1692,564,564,564,564,564,564,564,1692,564,1692,564,44268][9024,2256,564,96156][]

So all i need is a function that takes in the protocol, device, subdevice and function, and returns the start sequence int array

`import org.harctoolbox.irp.IrpTransmogrifier;

public int[] generateIr(String protocolName, int device, int subdevice, int function) {
    // TODO: Implement actual IR signal generation using IrpTransmogrifier library
    
    // Placeholder return value based on the example NEC1 output
        return new int[] {
            9024, 4512, 564, 564, 564, 564, 564, 1692, 564, 1692, 564, 564, 564, 564, 564, 564,
            564, 564, 564, 564, 564, 1692, 564, 564, 564, 564, 564, 564, 564, 1692, 564, 564,
            564, 564, 564, 564, 564, 564, 564, 564, 564, 1692, 564, 1692, 564, 1692, 564, 564,
            564, 564, 564, 1692, 564, 1692, 564, 1692, 564, 564, 564, 564, 564, 564, 564, 1692,
            564, 1692, 564, 44268
        };
}`

Could you please help me with this? Or perhaps tell me where I can find examples of API functions?

Thank you,

Luis

**Comment by bengtmartensson** [comment]
Nice. The best resource is the [Javadoc API documentation](https://bengtmartensson.github.io/IrpTransmogrifier/). There are also some examples [here](https://github.com/bengtmartensson/IrpTransmogrifier/tree/master/contributed/src/org/harctoolbox/example). Let me know if this is helps you.

Good luck,
Bengt

**Comment by luispl77** [comment]
Thank you for providing some examples, however, those are for decoding. I need to encode, or render, as you call it.

Im still struggling to find the solution here. I tried this:
```java

public int[] generateIr(String protocolName, int device, int subdevice, int function) {
        // Initialize IrpDatabase
        IrpDatabase irpDatabase = new IrpDatabase();

        // Initialize NameEngine and define parameters
        NameEngine nameEngine = new NameEngine();
        try {
            nameEngine.define("D", (long) device);
            nameEngine.define("S", (long) subdevice);
            nameEngine.define("F", (long) function);
        } catch (InvalidNameException e) {
            e.printStackTrace();
            // Return an empty array or handle the error as needed
            return new int[]{};
        }

        try {
            // Retrieve the NamedProtocol based on the protocol name
            NamedProtocol protocol = irpDatabase.getNamedProtocolExpandAlias(protocolName);

            if (protocol == null) {
                System.err.println("Protocol not found: " + protocolName);
                return new int[]{};
            }

            // Render the IR signal using the protocol and NameEngine
            IrSignal irSignal = protocol.render(nameEngine);

            // Convert the IrSignal to an int array using toIntArray with a count of 1
            // You can adjust the count as needed for multiple repetitions
            return irSignal.toIntArray(1);
        } catch (UnknownProtocolException e) {
            System.err.println("Unknown protocol: " + protocolName);
            e.printStackTrace();
        } catch (OddSequenceLengthException | DomainViolationException | UnsupportedRepeatException |
                 IrpInvalidArgumentException | NameUnassignedException e) {
            // Handle specific exceptions related to IR signal generation
            e.printStackTrace();
        } catch (Exception e) {
            // Handle any other unforeseen exceptions
            e.printStackTrace();
        }

        // Return an empty array in case of any errors
        return new int[]{};
    }
```


And now I get a "Unknown Protocol error", from calling `generateIr("NEC", 12, 34, 56)`:

`org.harctoolbox.irp.UnknownProtocolException: Protocol NEC not found.`

**Comment by luispl77** [comment]
Yes i had previously tried with NEC1 as well. It also gives the same error
Also tried others
` org.harctoolbox.irp.UnknownProtocolException: Protocol NEC1 not found.`
`org.harctoolbox.irp.UnknownProtocolException: Protocol NEC1-f16 not found.`


Could it be because I am in Android environment, it is not loading the IrpProtocols.xml properly?

My current dependencies:

```
implementation 'org.harctoolbox:IrpTransmogrifier:1.2.11'
implementation 'com.beust:jcommander:1.78'
implementation 'org.antlr:antlr-runtime:3.5.2'
```

But is the code at least correct as far as you can see?

**Comment by luispl77** [comment]
I have found what the issue is. The XML parsing is not available on Android platform. 

```java
public int[] generateIr(String protocolName, int device, int subdevice, int function) {
        // Initialize IrpDatabase
        IrpDatabase irpDatabase;

        try {
            // Initialize IrpDatabase
            irpDatabase = new IrpDatabase((String) null);
        } catch (IOException | IrpParseException | SAXException e) {
            System.err.println("Error initializing IrpDatabase: " + e.getMessage());
            e.printStackTrace();
            return new int[]{};
        }

        // Initialize NameEngine and define parameters
        NameEngine nameEngine = new NameEngine();
        try {
            nameEngine.define("D", (long) device);
            nameEngine.define("S", (long) subdevice);
            nameEngine.define("F", (long) function);
        } catch (InvalidNameException e) {
            e.printStackTrace();
            // Return an empty array or handle the error as needed
            return new int[]{};
        }

        try {
            // Retrieve the NamedProtocol based on the protocol name
            NamedProtocol protocol = irpDatabase.getNamedProtocolExpandAlias(protocolName);

            if (protocol == null) {
                System.err.println("Protocol not found: " + protocolName);
                return new int[]{};
            }

            // Render the IR signal using the protocol and NameEngine
            IrSignal irSignal = protocol.render(nameEngine);

            // Convert the IrSignal to an int array using toIntArray with a count of 1
            // You can adjust the count as needed for multiple repetitions
            return irSignal.toIntArray(1);
        } catch (UnknownProtocolException e) {
            System.err.println("Unknown protocol: " + protocolName);
            e.printStackTrace();
        } catch (OddSequenceLengthException | DomainViolationException | UnsupportedRepeatException |
                 IrpInvalidArgumentException | NameUnassignedException e) {
            // Handle specific exceptions related to IR signal generation
            e.printStackTrace();
        } catch (Exception e) {
            // Handle any other unforeseen exceptions
            e.printStackTrace();
        }

        // Return an empty array in case of any errors
        return new int[]{};
    }
```

```
Caused by: java.lang.IllegalArgumentException: http://www.w3.org/2001/XMLSchema
                                                                                                    	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:192)
                                                                                                    	at org.harctoolbox.xml.XmlUtils.<clinit>(XmlUtils.java:122)
                                                                                                    	at org.harctoolbox.xml.XmlUtils.openXmlStream(XmlUtils.java:168) 
                                                                                                    	at org.harctoolbox.irp.IrpDatabase.openXmlStream(IrpDatabase.java:192) 
                                                                                                    	at org.harctoolbox.irp.IrpDatabase.<init>(IrpDatabase.java:242) 
                                                                                                    	at org.harctoolbox.irp.IrpDatabase.<init>(IrpDatabase.java:250) 
```


So, is there any way to get around this without modifying the library? Thanks

**Comment by bengtmartensson** [comment]
If "The XML parsing is not available on Android platform"  classes like javax.xml.validation.Schema would been missing, not misbehaving. The program would bomb immediately at start complaing about missing classes, instead of IllegalArgumentException.

I get the impression that you are not using a debugger...

**Comment by luispl77** [comment]
Sorry I cannot step line by line inside an external library from Android studio unfortunately. I can give you the full trace

`irpDatabase = new IrpDatabase((String) null);` this is where it last goes inside my code. the rest is your library:

```
FATAL EXCEPTION: main
Process: com.masked.project, PID: 26340
java.lang.ExceptionInInitializerError
	at org.harctoolbox.xml.XmlUtils.openXmlStream(XmlUtils.java:168)
	at org.harctoolbox.irp.IrpDatabase.openXmlStream(IrpDatabase.java:192)
	at org.harctoolbox.irp.IrpDatabase.<init>(IrpDatabase.java:242)
	at org.harctoolbox.irp.IrpDatabase.<init>(IrpDatabase.java:250)
	at com.masked.project.ui.sampler.RawModeFragment.generateIr(RawModeFragment.java:557)
	at com.masked.project.ui.sampler.RawModeFragment.lambda$onCreateView$3$com-masked-project-ui-sampler-RawModeFragment(RawModeFragment.java:160)
	at com.masked.project.ui.sampler.RawModeFragment$$ExternalSyntheticLambda5.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7498)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:7475)
	at android.view.View.access$3600(View.java:833)
	at android.view.View$PerformClick.run(View.java:28673)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalArgumentException: http://www.w3.org/2001/XMLSchema
	at javax.xml.validation.SchemaFactory.newInstance(SchemaFactory.java:192)
	at org.harctoolbox.xml.XmlUtils.<clinit>(XmlUtils.java:122)
	at org.harctoolbox.xml.XmlUtils.openXmlStream(XmlUtils.java:168)
	at org.harctoolbox.irp.IrpDatabase.openXmlStream(IrpDatabase.java:192)
	at org.harctoolbox.irp.IrpDatabase.<init>(IrpDatabase.java:242)
	at org.harctoolbox.irp.IrpDatabase.<init>(IrpDatabase.java:250)
	at com.masked.project.ui.sampler.RawModeFragment.generateIr(RawModeFragment.java:557)
	at com.masked.project.ui.sampler.RawModeFragment.lambda$onCreateView$3$com-masked-project-ui-sampler-RawModeFragment(RawModeFragment.java:160)
	at com.masked.project.ui.sampler.RawModeFragment$$ExternalSyntheticLambda5.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7498)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:7475)
	at android.view.View.access$3600(View.java:833)
	at android.view.View$PerformClick.run(View.java:28673)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
I suspect Android might not include a full implementation of the W3C XML Schema validation (not parsing as I mistakenly said before). What are your thoughts?

**Comment by bengtmartensson** [comment]
It appears that the [SchemaFactory sometimes fails and then throws IllegalArgumentException](https://docs.oracle.com/javase/8/docs/api/javax/xml/validation/SchemaFactory.html#newInstance-java.lang.String-).  I'll see if I can extend the code to take care of this case; stay tuned...

> `implementation 'org.harctoolbox:IrpTransmogrifier:1.2.11'`

Current is 1.2.13.
